
INSERT INTO public.email_templates (slug, nome, assunto, conteudo_html, categoria, variaveis, is_active)
VALUES
  ('evento-convite-participar', 'Convite para Evento', 'Você está convidado(a) para {{evento_nome}}!', '<div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;padding:20px"><h1 style="color:#1a365d">Você está convidado(a)!</h1><p>Olá <strong>{{nome}}</strong>,</p><p>Temos o prazer de convidá-lo(a) para o evento <strong>{{evento_nome}}</strong>.</p><p>📅 <strong>Data:</strong> {{evento_data}}</p><p>🕐 <strong>Horário:</strong> {{evento_hora}}</p><p>📍 <strong>Local:</strong> {{evento_local}}</p><p>{{evento_descricao}}</p><div style="text-align:center;margin:30px 0"><a href="{{link_inscricao}}" style="background-color:#2563eb;color:#fff;padding:14px 28px;text-decoration:none;border-radius:8px;font-weight:bold">Confirmar Presença</a></div><p style="color:#6b7280;font-size:12px">Se não deseja mais receber nossas comunicações, <a href="{{link_descadastro}}">clique aqui</a>.</p></div>', 'evento', '["nome","evento_nome","evento_data","evento_hora","evento_local","evento_descricao","link_inscricao","link_descadastro"]', true),

  ('captacao-convite-material', 'Convite para Material', 'Confira: {{material_nome}}', '<div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;padding:20px"><h1 style="color:#1a365d">Material Exclusivo</h1><p>Olá <strong>{{nome}}</strong>,</p><p>Preparamos um material especial para você: <strong>{{material_nome}}</strong>.</p><p>{{material_descricao}}</p><div style="text-align:center;margin:30px 0"><a href="{{link_material}}" style="background-color:#2563eb;color:#fff;padding:14px 28px;text-decoration:none;border-radius:8px;font-weight:bold">Acessar Material</a></div><p style="color:#6b7280;font-size:12px">Se não deseja mais receber nossas comunicações, <a href="{{link_descadastro}}">clique aqui</a>.</p></div>', 'captacao', '["nome","material_nome","material_descricao","link_material","link_descadastro"]', true),

  ('pesquisa-convite', 'Convite para Pesquisa', 'Sua opinião é importante!', '<div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;padding:20px"><h1 style="color:#1a365d">Queremos ouvir você!</h1><p>Olá <strong>{{nome}}</strong>,</p><p>Sua opinião é muito importante para nós. Participe da nossa pesquisa e ajude-nos a melhorar.</p><div style="text-align:center;margin:30px 0"><a href="{{link_pesquisa}}" style="background-color:#2563eb;color:#fff;padding:14px 28px;text-decoration:none;border-radius:8px;font-weight:bold">Responder Pesquisa</a></div><p style="color:#6b7280;font-size:12px">Se não deseja mais receber nossas comunicações, <a href="{{link_descadastro}}">clique aqui</a>.</p></div>', 'pesquisa', '["nome","link_pesquisa","link_descadastro"]', true),

  ('lideranca-evento-convite', 'Convite para Evento (Líderes)', 'Convite especial: {{evento_nome}}', '<div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;padding:20px"><h1 style="color:#1a365d">Convite Especial para Lideranças</h1><p>Olá <strong>{{nome}}</strong>,</p><p>Convidamos você e sua rede para o evento <strong>{{evento_nome}}</strong>.</p><p>📅 <strong>Data:</strong> {{evento_data}}</p><p>🕐 <strong>Horário:</strong> {{evento_hora}}</p><p>📍 <strong>Local:</strong> {{evento_local}}</p><p>Compartilhe seu link personalizado com seus contatos:</p><div style="text-align:center;margin:20px 0;padding:15px;background:#f3f4f6;border-radius:8px"><a href="{{link_inscricao_afiliado}}" style="color:#2563eb;font-weight:bold;word-break:break-all">{{link_inscricao_afiliado}}</a></div><div style="text-align:center;margin:30px 0"><a href="{{link_inscricao}}" style="background-color:#2563eb;color:#fff;padding:14px 28px;text-decoration:none;border-radius:8px;font-weight:bold">Confirmar Minha Presença</a></div></div>', 'lideranca', '["nome","evento_nome","evento_data","evento_hora","evento_local","link_inscricao","link_inscricao_afiliado"]', true),

  ('lideranca-pesquisa-link', 'Link de Pesquisa (Líderes)', 'Compartilhe: Pesquisa de Opinião', '<div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;padding:20px"><h1 style="color:#1a365d">Link de Pesquisa</h1><p>Olá <strong>{{nome}}</strong>,</p><p>Compartilhe o link abaixo com seus contatos para que participem da pesquisa:</p><div style="text-align:center;margin:20px 0;padding:15px;background:#f3f4f6;border-radius:8px"><a href="{{link_pesquisa_afiliado}}" style="color:#2563eb;font-weight:bold;word-break:break-all">{{link_pesquisa_afiliado}}</a></div><div style="text-align:center;margin:30px 0"><a href="{{link_pesquisa_afiliado}}" style="background-color:#2563eb;color:#fff;padding:14px 28px;text-decoration:none;border-radius:8px;font-weight:bold">Acessar Link</a></div></div>', 'lideranca', '["nome","link_pesquisa_afiliado"]', true),

  ('lideranca-reuniao-link', 'Link de Reunião (Líderes)', '{{deputado_nome}} - Seu link de indicação', '<div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;padding:20px"><h1 style="color:#1a365d">Seu Link de Indicação</h1><p>Olá <strong>{{nome}}</strong>,</p><p>Compartilhe seu link personalizado de indicação para o gabinete do(a) <strong>{{deputado_nome}}</strong>:</p><div style="text-align:center;margin:20px 0;padding:15px;background:#f3f4f6;border-radius:8px"><a href="{{link_reuniao_afiliado}}" style="color:#2563eb;font-weight:bold;word-break:break-all">{{link_reuniao_afiliado}}</a></div><p>Cada pessoa que agendar uma visita através do seu link contará como uma indicação sua!</p></div>', 'lideranca', '["nome","deputado_nome","link_reuniao_afiliado"]', true),

  ('lideranca-cadastro-link', 'Link de Cadastro (Líderes)', 'Seu link para cadastrar novas lideranças', '<div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;padding:20px"><h1 style="color:#1a365d">Link de Cadastro</h1><p>Olá <strong>{{nome}}</strong>,</p><p>Use o link abaixo para convidar novas lideranças para a rede:</p><div style="text-align:center;margin:20px 0;padding:15px;background:#f3f4f6;border-radius:8px"><a href="{{link_cadastro_afiliado}}" style="color:#2563eb;font-weight:bold;word-break:break-all">{{link_cadastro_afiliado}}</a></div><div style="text-align:center;margin:30px 0"><a href="{{link_cadastro_afiliado}}" style="background-color:#2563eb;color:#fff;padding:14px 28px;text-decoration:none;border-radius:8px;font-weight:bold">Compartilhar Link</a></div></div>', 'lideranca', '["nome","link_cadastro_afiliado"]', true),

  ('validacao-cadastro-email', 'Validação de Cadastro', 'Confirme seu cadastro', '<div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;padding:20px"><h1 style="color:#1a365d">Confirme seu Cadastro</h1><p>Olá <strong>{{nome}}</strong>,</p><p>Para validar seu cadastro, clique no botão abaixo:</p><div style="text-align:center;margin:30px 0"><a href="{{link_verificacao}}" style="background-color:#2563eb;color:#fff;padding:14px 28px;text-decoration:none;border-radius:8px;font-weight:bold">Confirmar Cadastro</a></div><p style="color:#6b7280;font-size:12px">Se você não solicitou este cadastro, ignore este email.</p></div>', 'verificacao', '["nome","link_verificacao"]', true),

  ('material-regiao-email', 'Material por Região', 'Material disponível na sua região!', '<div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;padding:20px"><h1 style="color:#1a365d">Material Disponível</h1><p>Olá <strong>{{nome}}</strong>,</p><p>Informamos que o material <strong>{{material_nome}}</strong> está disponível na sua região.</p><p>{{material_descricao}}</p><div style="text-align:center;margin:30px 0"><a href="{{link_material}}" style="background-color:#2563eb;color:#fff;padding:14px 28px;text-decoration:none;border-radius:8px;font-weight:bold">Ver Detalhes</a></div><p style="color:#6b7280;font-size:12px">Se não deseja mais receber nossas comunicações, <a href="{{link_descadastro}}">clique aqui</a>.</p></div>', 'material', '["nome","material_nome","material_descricao","link_material","link_descadastro"]', true)

ON CONFLICT (slug) DO NOTHING;
